### PR TITLE
Adding Steven Deobald. That's me!

### PR DESCRIPTION
**Pull request by deobald**
Hi Nemo! Happy to offer up my couch. Thanks for building this!

### CODE REVIEW

**Comment by captn3m0** [comment]
A couple of fixes needed:
- You misspelled your twitter handle
- Your blog doesn't support HTTPS, so the build failed it
- Needs to be your facebook username instead of the profile URL.

I'll try to add detection for the last thing to support both urls and usernames, but for now, the url has become: https://facebook.com/https://www.facebook.com/steven.deobald :(

Thanks for the PR :+1:

**Comment by deobald** [comment]
> Your blog doesn't support HTTPS, so the build failed it

Which implies what, as a solution?

**Comment by deobald** [comment]
Wow. I'm not sure where that HTTPS came from... I thought you meant the build required HTTPS. ;) Sorry, my bad. Will fix.

**Comment by deobald** [comment]
Fixen. Sorry about that.

**Comment by captn3m0** [comment]
Yeah, I'm still not sure if running html-proofer is a good idea or a bad one. But it has caught a couple of issues like this, so I think I'll keep it. The issue is that if your blog goes down, someone else's PR might fail at a later date. Don't have a real solution for that.

**Comment by ppaeps** [comment]
On 2015-11-23 12:55:01 (+0530), Nemo notifications@github.com wrote:

> Yeah, I'm still not sure if running html-proofer is a good idea or a 
> bad one. But it has caught a couple of issues like this, so I think 
> I'll keep it. The issue is that if your blog goes down, someone else's 
> PR might fail at a later date. Don't have a real solution for that.

Perhaps you can run the checker in a cronjob to catch borken links 
before they break someone else's build?

## 

Philip Paeps
Senior Reality Engineer
Ministry of Information

**Comment by captn3m0** [comment]
Nice idea. Will set it up when I get some time.

**Pull request merged**
