### PR TITLE
Chaitanyanettem add testing

### PR DESCRIPTION
**Pull request by captn3m0**
- Closes #79 
- Easier to collaborate on a local branch, now that @chaitanyanettem has access.

### CODE REVIEW

**Comment by chaitanyanettem** [comment]
Hmm. I tried updating Gemfile.lock like the error message indicated in https://travis-ci.org/hackercouch/hackercouch/builds/111462278

That didn't work. This is the same issue from #79. Any suggestions?

**Comment by chaitanyanettem** [comment]
Also yay for access! :smile:

**Comment by captn3m0** [comment]
I think it was a ruby version issue because of a ruby-version file commited
in the repo or something similar. Would be nice if you can take a look and
ship this ;)

**Comment by chaitanyanettem** [comment]
This is weird. I cannot reproduce this issue locally without having ruby version set to ~~2.3.1~~ 2.3.0 :frowning: Hmm.

**Comment by captn3m0** [comment]
Upgrading to 2.3.1 and giving this a try

**Pull request closed without merging**
