### PR TITLE
[WIP] Add Gravatar

### PR DESCRIPTION
**Pull request by simison**
_Work in progress, please don't merge yet._

image

http://en.gravatar.com/site/implement/images/

`md5` filter doesn't work for me, but might be just because of Jekyll 3? Wanna test this @captn3m0?

### CODE REVIEW

**Comment by simison** [comment]
Obs, accidentally included bunch of other commits to this one. Will clean out + squash later.

**Comment by simison** [comment]
image

**Comment by captn3m0** [comment]
Since you have commit rights, you should ideally be working on the upstream repo, so others can contribute to the same branch easily.

I'll take a look at gravatar.

**Comment by captn3m0** [comment]
So, the liquid gem doesn't support md5: https://github.com/jekyll/jekyll/issues/2491. Shopify's internal version does.

**Comment by simison** [comment]
> Since you have commit rights, you should ideally be working on the upstream repo, so others can contribute to the same branch easily.

Good point! Closing this, continue discussion at #40 and https://github.com/captn3m0/hackercouch/tree/gravatar

_(edited discussion issue number)_

**Pull request closed without merging**
