### PR TITLE
couches: Add Arthur

### PR DESCRIPTION
**Pull request by kprovost**
Adding my couch (Grimbergen/BE).

### CODE REVIEW

**Comment by captn3m0** [comment]
Thanks Arthur. Will merge it asap. The github Android client doesn't have a merge button that I can find.

**Comment by Haroenv** [comment]
Why does it say Arthur, while in the other information Kristof? Just wondering

**Comment by kprovost** [comment]
Arthur (or _arthur_ on IRC) is my nickname. Kristof is my real[1](first) name.

[1] What the Belgian government thinks my name is.

**Comment by Haroenv** [comment]
No problem, was just confusing :)

**Pull request merged**
