### PR TITLE
Add daiyi couch

### PR DESCRIPTION
**Pull request by daiyi**
:wave:

### CODE REVIEW

**Comment by captn3m0** [comment]
Thanks :100:

**Comment by simison** [comment]
👋 

@Simsadz would've been coming to NYC in May. :-) Next time!

**Comment by daiyi** [comment]
👋👋✨

That is the unfortunate part about traveling, being unable to host to others simultaneously (': hopefully we'll run into each other elsewhere!

**Comment by ppaeps** [comment]
On 2017-03-10 17:08:09 (+0900), chris⚡ <notifications@github.com> wrote:
> That is the unfortunate part about traveling, being unable to host
> to others simultaneously (': hopefully we'll run into each other
> elsewhere!

There are key exchange protocols to work around this.  I'm handing my
spare key to someone in Singapore next weekend to give to someone who is
staying at my place in Belgium while I'm in Hong Kong later this month.

You're never more than one or two conferences removed from any other
hacker?

-- 
Philip Paeps
Senior Reality Engineer
Ministry of Information

**Pull request merged**
