### PR TITLE
Revert "Delete lut4rp.md"

### PR DESCRIPTION
**Pull request by simison**
Reverts hackercouch/hackercouch#159

### CODE REVIEW

**Comment by simison** [comment]
Does this look correct to you @pratul ?

You can update your profile description in a separate PR if you'd like.

**Comment by simison** [comment]
Oops, looks like revert included reverting my own profile change that I made after removing yours. Rebasing.

**Comment by pratul** [comment]
LGTM

**Comment by captn3m0** [comment]
Thanks @simison :+1:

**Pull request merged**
