### PR TITLE
Add mariha.md

### PR DESCRIPTION
**Pull request by mariha**
One more welcoming hacker somewhere out there in the world.

### CODE REVIEW

**Review by captn3m0 — APPROVED** [review]

**Comment by captn3m0** [comment]
Thanks a lot!

**Comment by captn3m0** [comment]
We're facing some deployment issues due to Travis, will get this deployed soon 👍🏽

**Comment by captn3m0** [comment]
We're finally live 🎉: https://hackercouch.com/couches/mariha.html

Sorry about the delay, had to switch from Travis to GitHub Actions.

**Comment by mariha** [comment]
Thanks!

**Pull request merged**
