### PR TITLE
Cities on map

### PR DESCRIPTION
**Pull request by captn3m0**
Includes work by @krsoninikhil. I refactored slightly to remove the json by-hand generator.

The only thing missing is a cache support, and as a result the generator is very slow. Since this is run on every build, it makes testing and working on hackercouch really slow.

Travis supports proper file-based caches (every build gets the same cache). We can use that to store the API responses from nominatim.

### CODE REVIEW

**Comment by captn3m0** [comment]
@krsoninikhil I've added cache support, so now the builds are running pretty fast. Also added geo.json to gitignore since its not meant to be committed. You can merge this once you have reviewed it :+1:

**Comment by krsoninikhil** [comment]
That's better, I didn't know about the api response caching, thanks for pointing out.
But why the cache data is added in .gitignore, can't travis build also just use the cache generated on local build?

**Comment by krsoninikhil** [comment]
Its getting some issues with not importing leaflet over https

**Comment by captn3m0** [comment]
We don't want to commit the cache to git, because its not the "source" for the repo, and can always be regenerated.

**Comment by krsoninikhil** [comment]
Okay.

**Pull request merged**
