### PR TITLE
Create raincrash.md

### PR DESCRIPTION
**Pull request by raincrash**

### CODE REVIEW

**Comment by captn3m0** [comment]
Not sure if we have codeblock support. I'll upgrade to jekyll 3 and merge this with a few changes :+1:

**Comment by raincrash** [comment]
Seem's like there's no codeblock support yet. Removed the note :+1:

**Comment by captn3m0** [comment]
Re-ran the build and it passed. Merging now. Will post a note here once we have codeblocks support.

**Comment by raincrash** [comment]
@captn3m0 Thanks a ton. :+1:

**Pull request merged**
