### PR TITLE
Create archetana.md

### PR DESCRIPTION
**Pull request by archetana**

### CODE REVIEW

**Comment by captn3m0** [comment]
@archetana Do you mind fixing the name and the city spelling?

**Comment by archetana** [comment]
Fixed, please check

**Comment by captn3m0** [comment]
Thanks a lot for the contribution 👍

**Comment by captn3m0** [comment]
@archetana I somehow missed it during the initial review, but this is missing details about the accommodation.

Can you file a PR adding some details?

**Pull request merged**
