### PR TITLE
Make it easier to run local installations

### PR DESCRIPTION
**Pull request by ppaeps**
This builds on @simison's work in #41.  Makes it a little easier for hackers unfamiliar with the web environment to hack on Hackercouch.  I learned about RVM from FOSDEM a couple of years ago and found a `setup-env.sh` script like this to be helpful.  If there are better ways to set up light(ish)-weight environments for hacking on web things, I'd love to have my mind expanded. :)

### CODE REVIEW

**Comment by simison** [comment]
Docker? :-)

**Comment by ppaeps** [comment]
> Docker? :-)

That's lightweight now? :)  Not on my planet! :)

**Comment by simison** [comment]
Tru dat.

**Comment by captn3m0** [comment]
Can you move the shell scripts to the `_scripts` directory. That way its not published to the web. (Anything in directories with `_` as prefix is ignored by Jekyll)

**Comment by ppaeps** [comment]
Done.

**Comment by simison** [comment]
@ppaeps @captn3m0 wanna add more bits into this or should we merge?

I'm very unfamiliar with Ruby gems so not sure if these should be added as well: https://github.com/simison/hackercouch-1/blob/fix-local-install/Gemfile#L3-L5 (extra gems and versions)?

...and if jekyll should be `~2.5` instead of `~>2.5`?

**Comment by captn3m0** [comment]
I am merging this for now. If we face any version issues, we can add those bits later.

**Comment by ppaeps** [comment]
I've got a bit more verbiage for `README.md` sitting in my tree.  I'll 
push it here later today and merge this afterwards.  Thanks for 
reminding me. :)

**Pull request merged**
