### PR TITLE
remove reggi

### PR DESCRIPTION
**Pull request by reggi**
Hey @captn3m0, I totally posted this with one fatal flaw, I don't have an extra set of keys yet which makes it logistically a little difficult to share my apartment. Can I be removed? Sorry for the inconvenience. If I manage to conjure another set of keys I'll love to be added back on, but until then I'd like to be removed.

### CODE REVIEW

**Comment by simison** [comment]
Shouldn't we have `_meetup` folder for this? :-)

**Comment by ppaeps** [comment]
Maybe we could annotate couches with an `available:` boolean?  But that'll cause a lot of repo-churn (and merge work!).  I think if a couch is unavailable for a long-time, just removing is the easiest option.  Removes can easily be reverted when the couch becomes available again.

**Comment by simison** [comment]
Valid point. How about letting people embed a Gist into their profile, so that they can easily update their description / availability?

**Comment by ppaeps** [comment]
If _merging a gist_ is the web-equivalent of `#include 
"something_under_couch_owner_control"`, I think that's a great idea!

Except that it might lead to spam?  Though if we limit where these 
_gists_ can be hosted, the spam could be made someone else's problem?

**Comment by simison** [comment]
I have inkling we won't stumble on spam issues anytime soon. :-)

There's this feature in Jekyll: https://github.com/jekyll/jekyll-gist

**Comment by captn3m0** [comment]
I don't want to use gists. They break linkability (iframes are not indexed). If I understand it, we need a faster way for people to update their hackercouch statuses. We need a way to limit the fields allowed via such a method, so as to prevent identity switches, for eg.

Keeping it limited to availability as a boolean might be a good way to start.

We could probably load the gist via JS and then show the contents, but thats not really ideal. Other ways would be to grab the data during the build and push that to a static server instead. I'll keep thinking..

**Pull request merged**
