### PR TITLE
Fix install

### PR DESCRIPTION
**Pull request by simison**
I couldn't get this working locally without these changes, but then I really don't know much about Ruby/gems.

Yet it looks like my Jekyll is on v3 since I probably installed it globally:

```
$ jekyll --version
jekyll 3.0.1
```

So I don't want to trust this installation to work with v2 without someone testing it first. :-)

@captn3m0 @ppaeps could you confirm if this would work?

### CODE REVIEW

**Comment by captn3m0** [comment]
Checked it out, tried locally. It works :+1:
Merged.

**Comment by simison** [comment]
Thanks.

Weird, I got an email notifying about failed CI:

> Build #101 was broken.

But here it seems fine: https://travis-ci.org/hackercouch/hackercouch/builds/94957765

Huh?

~~BTW I can't see Travis tests here at the PR view, but I can't remember where to change settings for that?~~

Edit, sorry, it probably just won't show it after merging. I can see Tracis-OK next to my commit:

image

**Comment by captn3m0** [comment]
The build was broken because a link (about.me) returned a 500. I reran the build after checking the URL manually and it fixed itself.

**Comment by simison** [comment]
:+1:

**Pull request merged**
