### PR TITLE
adrian couch

### PR DESCRIPTION
**Pull request by Raudaschl**

### CODE REVIEW

**Comment by simison** [comment]
Thanks! :+1:

**Comment by Raudaschl** [comment]
Thank you. really hope this idea takes off!

**Comment by captn3m0** [comment]
@simison I've changed the link the default yml to use `http://`. Less typo fixes going ahead.

**Comment by simison** [comment]
@captn3m0 :+1: I remember thinking of doing the same.

Thanks @Raudaschl!

**Pull request merged**
