### PR TITLE
Fix local install

### PR DESCRIPTION
**Pull request by simison**
Didn't want to push directly without review.

LGTY?

### CODE REVIEW

**Comment by simison** [comment]
I'm not very familiar with Jekyll nor Ruby, but I had to add `kramdown` before getting `jekyll serve` running.

Looks like I'm not getting truncated descriptions at the list, should I add some other gem to bundle as well for that?

**Comment by simison** [comment]
Reopening to re-run Travis.

**Comment by captn3m0** [comment]
I am guessing this might be because of `jekyll` jumping a major version to 3.0. I am pretty comfortable with 2.x, but haven't looked into 3 much. I'll review it locally once, if you can't get truncated descriptions to work.

**Comment by simison** [comment]
I didn't try to fix it. Should we add version numbers to Gemfile?

**Comment by captn3m0** [comment]
Ideally, yes so everyone is on the same version.

**Comment by ppaeps** [comment]
It would be helpful to have some documentation about how to run a local 
install.  The **development** section in README.md is a little thin.

**Comment by simison** [comment]
@ppaeps I added a "quickstart" section to readme at this PR, see: https://github.com/simison/hackercouch-1/blob/fix-local-install/README.md#quickstart

**Comment by ppaeps** [comment]
Thanks!  That's helpful.  I'll give it a go and update the _quickstart_ 
section if I run into trouble.

**Comment by simison** [comment]
Added versions to Gemfile.

**Pull request closed without merging**
