### PR TITLE
Verification of profiles

### PR DESCRIPTION
**Pull request by captn3m0**
**Plan**:
- [x] Publish verification hashes on couch
- [x] Write a verification guide
- [ ] Write script that does verifications (writes to verify.md)
- [ ] Read from verify.md
- [ ] Add this information to the API
- [ ](optional) discover verification posts on the build runs.

### CODE REVIEW

**Comment by simison** [comment]
Is there no way to get verifying via oAuth working?

**Comment by captn3m0** [comment]
Will have to run a separate server for just this. Maybe worth it...

**Comment by simison** [comment]
Yep! It's okay to have this hacky for users (it's hackercouch after all), but this Tweeting hash codes stuff is a bit cumbersome.

**Comment by simison** [comment]
That said, I'm not so sure if the whole excercise is worth the supposed safety gain. ;-) Jekyll 3 support (#89) would be more important?

**Comment by captn3m0** [comment]
Haha, you are right. This has been flying rudderless for a while. This PR was just an attempt to get me back at working on hackercouch.

**Comment by simison** [comment]
Ye totally, no worries, just saying. :-) Tinkering on random stuff is fun no matter what it is!

**Comment by captn3m0** [comment]
Closing this.

Instead looking to add keybase as a verification option.

**Pull request closed without merging**
